// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechAntenna.Infrastructure.Persistence;

#nullable disable

namespace TechAntenna.Infrastructure.Migrations;

[DbContext(typeof(TechAntennaDbContext))]
[Migration("20260803132000_AddTopics")]
partial class AddTopics
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TechAntenna.Core.Topics.StoredTopic", b =>
        {
            b.Property<string>("Tag")
                .HasColumnType("text");

            b.Property<int>("ArticleCount")
                .HasColumnType("integer");

            b.Property<int>("BookCount")
                .HasColumnType("integer");

            b.Property<DateTimeOffset>("CollectedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("EventCount")
                .HasColumnType("integer");

            b.HasKey("Tag");

            b.HasIndex("CollectedAt");

            b.ToTable("Topics");
        });
#pragma warning restore 612, 618
    }
}
