// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TechAntenna.Infrastructure.Persistence;

#nullable disable

namespace TechAntenna.Infrastructure.Migrations;

[DbContext(typeof(TechAntennaDbContext))]
[Migration("20260803143000_AddTrendTopicMetadata")]
partial class AddTrendTopicMetadata
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
